spring.application.name=aura-store

spring.datasource.url=jdbc:postgresql://localhost:5433/auraStore
spring.datasource.username=postgres
spring.datasource.password=Shivam@4321dev

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
